// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7: CLI (migrate, db push, introspection) uses this URL — use a direct Postgres URL, not the pooler.
  // App runtime should use PrismaClient with @prisma/adapter-pg and DATABASE_URL (pooled). See src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
